services:
  # Nginx Reverse Proxy Service
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose port 80 for Nginx on the host
    depends_on:
      - frontend  # Ensure the frontend is available
      - backend   # Ensure the backend is available
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html

  # React frontend Service
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Expose port 3000 on the host machine and map it to port 80 in the container
    depends_on:
      - backend  # Ensure that the backend service is started before the frontend

  # FastAPI backend Service
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose port 8000 on the host machine and map it to port 8000 in the container
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db-dev  # Ensure that the MySQL database is available before the backend starts

  # MySQL Database Service
  db-dev:
    image: mysql:8.0
    container_name: db-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"  # Expose port 3306 for MySQL database (host:container)
    volumes:
      - mysql-data:/var/lib/mysql  # Use a Docker volume to persist MySQL data between container restarts

volumes:
  mysql-data:  # Define a named volume to store MySQL data persistently